---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    kbld.k14s.io/images: |
      - origins:
        - resolved:
            tag: 1.0.0
            url: quay.io/failk8s/testapp-package:1.0.0
        url: quay.io/failk8s/testapp-package@sha256:38810bd538d57460fb6e6c5f33945570ecc54598e1bbb7e3d7b73aa0acf94d67
  name: testapp.dev.failk8s.com.1.0.0
  namespace: kapp-controller-packaging-global
spec:
  refName: testapp.dev.failk8s.com
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
      fetch:
      - imgpkgBundle:
          image: quay.io/failk8s/testapp-package@sha256:38810bd538d57460fb6e6c5f33945570ecc54598e1bbb7e3d7b73aa0acf94d67
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  version: 1.0.0
