---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    kbld.k14s.io/images: |
      - origins:
        - resolved:
            tag: 1.1.0
            url: quay.io/failk8s/testapp-package:1.1.0
        url: quay.io/failk8s/testapp-package@sha256:f7f7a40c6c53b86e7c0bab87440d9c1c321c22408a8a43cbbdab3923b0378d01
  name: testapp.dev.failk8s.com.1.1.0
spec:
  refName: testapp.dev.failk8s.com
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
      fetch:
      - imgpkgBundle:
          image: quay.io/failk8s/testapp-package@sha256:f7f7a40c6c53b86e7c0bab87440d9c1c321c22408a8a43cbbdab3923b0378d01
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  version: 1.1.0
